Issue 188
w3c/html-aam pull request #214
Opened 2019-06-17 16:38 UTC by scottaohara

Closes #188 

removed element mappings for:
- a with parent menu
- button with parent menu
- input type=checkbox with parent menu
- input type=image with parent menu
- input type=radio with parent menu
- menuitem type=checkbox
- menuitem type=command
- menuitem type=radio

removed attribute mappings for:
- checked referencing menuitem types
- disabled referencing menuitem
- icon for menuitem element
- label referencing menu and menuitem elements
- radiogroup for menuitem element
- title for menuitem element

menu updated to map to role=list
  - add comment for info on role=menu to see ARIA

2019-06-18 11:00 UTC, stevefaulkner requested changes

2019-06-18 11:00 UTC, stevefaulkner commented on index.html
> +                The <a data-cite="HTML">`menu`</a> element is a semantic alternative to the <a data-cite="HTML">`ul`</a> element, and has no implemented mappings or behavior similar to ARIA's <a clas
suggest rewording "has no implemented mappings or behavior similar to ARIA's <a class="core-mapping" href="#role-map-menu">`role="menu"`</a>"

to "has no implemented mappings or behavior that reflect the semantics of the ARIA <a class="core-mapping" href="#role-map-menu">`menu`</a> role.

2019-06-18 13:30 UTC, scottaohara commented on index.html
> +                The <a data-cite="HTML">`menu`</a> element is a semantic alternative to the <a data-cite="HTML">`ul`</a> element, and has no implemented mappings or behavior similar to ARIA's <a clas
updated

2019-07-10 16:11 UTC, stevefaulkner approved these changes

2019-07-22 19:57 UTC, scottaohara commented
Added "not ready for merge" label as there are some issues that need to be addressed outside of this PR before merging.

2019-08-25 14:09 UTC, scottaohara commented
Adding todo item of adding a link in the comment section for `menu` to point to HTML's obsolete section.

- [ ] add https://html.spec.whatwg.org/multipage/obsolete.html#attr-menu-type

2019-09-11 13:31 UTC, scottaohara commented
latest push completes todo to reference/link to obsolete `menuitem` and `menu type` in HTML spec.  changelog date updated.  this will also close #237 which is duplicate to this PR.

2019-09-11 17:22 UTC, stevefaulkner approved these changes

2019-09-11 17:22 UTC, merged