Updating HTML elements to map to their Aria 1.2 roles
w3c/html-aam pull request #348
Opened 2021-09-29 19:12 UTC by scottaohara

This pull request updates many elements to match the new roles introduced in ARIA 1.2 (working through issue #229), and which are in core aam.  The updated elements are as follows:

* blockquote
* caption
* code
* del
* em
* ins
* meter
* paragraph
* strong
* sub
* sup
* time

*NOTE:* I have not presently updated the mapping for `figcaption` to the `caption` role.  At various times, people have expressed their unhappiness with the `figcaptoin` element's current behavior, and the redundancy / verbosity impacts it has as the accessible name for `figure`.  @jnurthen I would like to add this as a future agenda item to the ARIA wg call - specifically the group's feelings on changing `figcaption` to provide a description, rather than name – or some other alternative.

Additionally, this PR fixes the mappings for `body`, `html` (closes #330) and `hgroup` (closes #331)
* body maps to `generic` (related to #346)
* html maps to `document`
* hgroup maps to `generic` (related to #346)

Further, some updates to remove the mention of "?" cells from the 3.4 introduction, and that UAs must not expose `aria-roledescription` on generic elements.

Lastly, this PR updates the following elements which map to `generic` (or will map to `generic` under certain conditions).  This, along with the updates to `body` and `hgroup` starts the work on #346.

2021-09-29 20:45 UTC, stevefaulkner approved these changes

2021-10-26 11:49 UTC, scottaohara commented
per my mention about speaking to the WG regarding `figcaption`, there was consensus in the working group to _not_ have `figcaption` contribute to the accessible name of a `figure`.  instead, it was suggested that an `aria-details` association between the `figure` and the `figcaption` seemed to make the most sense, since a `figcaption` can contain structured and interactive content that would be less meaningful as a flattened text string (name or description).

all that said, this PR will not be updated to map `figcaption` to the `caption` role

2021-11-02 15:04 UTC, joanmarie requested changes
See my comments related to the `details` mapping change.

2021-11-02 15:04 UTC, joanmarie commented on index.html
> +                <a class="core-mapping" href="#role-map-generic">`generic`</a> role
Not sure about this one. At least for ATK, that is going to make the mapping for `details` be like `div` (`ATK_ROLE_SECTION`). The current mapping (`ATK_ROLE_PANEL`)  is what you get from a `group`.

2021-11-02 15:04 UTC, joanmarie commented on index.html
> -                  <span class="type">Localized Control Type:</span> `"details"`
This is getting lost.

2021-11-02 15:04 UTC, joanmarie commented on index.html
> -                  <span class="type">Relations:</span> `ATK_RELATION_DETAILS_FOR`
This is getting lost.

Aside: I think IA2 added a similar relationship that might be applicable.

2021-11-02 19:38 UTC, scottaohara commented on index.html
> +                <a class="core-mapping" href="#role-map-generic">`generic`</a> role
thank you for the catch.  I've reverted/revised the mistakes

2021-11-04 17:04 UTC, joanmarie approved these changes

2021-11-04 17:05 UTC, joanmarie commented
LGTM. Thanks!

2021-11-07 18:39 UTC, merged