update / expand input value mappings
w3c/html-aam pull request #396
Opened 2022-04-15 14:24 UTC by scottaohara

This PR closes #314 and clarifies the `value` attribute mappings for other input types.
note: the `value` attribute only represents *the initial value* for the input elements that expose the attribute's value.  If a user updates a form control the `value` attribute's value does not mutate to reflect the updated entry.  The updates I provided for these inputs attempts to specifically call this out.  if this is not clear, please suggest alternate wording.

Note that the `input type=color` `value` is far more complex than the other inputs and I would appreciate specific feedback on what would need to be updated here, if anything.

Additionally, the `input type=color` seems to make a strong case for allowing `aria-valuetext` on a `button` element – where the button should be named via a `label` or an `aria-label/labelledby`, but still needs to expose it's displayed value (subtree of the button element).

**NOTE:** due to the still broken table/details/summary script with respec, to view the updated table in the preview, you can add this style via devtools:
```
#html-attribute-state-and-property-mappings .table-container {
  display: block !important;
}
```
or find the `.table-container` that has the `display: none` on it, and turn that off.

fun...

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/pull/396.html" title="Last updated on Oct 26, 2022, 1:25 PM UTC (0e75d89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/396/a5ada74...0e75d89.html" title="Last updated on Oct 26, 2022, 1:25 PM UTC (0e75d89)">Diff</a>

2022-04-22 19:55 UTC, spectranaut reviewed
Still trying to catch up and get all the context for this change, i have a few questions to start!

2022-04-22 19:55 UTC, spectranaut commented on index.html
> +                  <a data-cite="accname-1.2/#dfn-accessible-description">accessible description</a>, or is not mapped (see comments).
I don't mean to nitpick, but these 4 changes belong in a separate editorial PR, don't you think?

2022-04-22 19:55 UTC, spectranaut commented on index.html
> +      <h3>`input type="text"`, `input type="password"`, `input type="search"`, `input type="tel"`, `input type="url"` and `textarea` Element</h3>
can these and the updates from 1.1->1.2 also be in a separate editorial PR, and not be held back by any discussion of value? :)

2022-04-22 19:55 UTC, spectranaut commented on index.html
> +                If specified, expose the value of the attribute as the initial value entry of the `input` element.
Specifically, what is the "value entry of the `input` element"?

Do we have the following specified somewhere: if, in one of these inputs, a user has entered text, how that text surfaced in the different accessibility APIs? If so we should link to it if not we should add it?

2022-04-22 19:55 UTC, spectranaut commented on index.html
> +                  If specified, expose the value of the attribute as the initial value of the `input`. User Agents MUST expose the modified value of the input to the <a class="termref">accessibility
Do these user agents MUSTs apply to the other inputs as well?

2022-04-27 20:43 UTC, scottaohara commented on index.html
> +                  <a data-cite="accname-1.2/#dfn-accessible-description">accessible description</a>, or is not mapped (see comments).
we talked about this.  bad habits. oops.  next time won't do!

2022-04-27 21:06 UTC, spectranaut requested changes
From our conversation!

2022-04-27 21:06 UTC, spectranaut commented on index.html
> +                If specified, expose the value of the attribute as the initial value entry of the `input` element.
As we discussed, let's use the same language here as in the HTML spec: https://html.spec.whatwg.org/multipage/input.html#attr-input-value

which I think would be (but check my work):
```
If specified, expose the content value attribute as the default value entry of the `input` element.
```

2022-04-27 21:06 UTC, spectranaut commented on index.html
> +                  If specified, expose the value of the attribute as the initial value of the `input`. User Agents MUST expose the modified value of the input to the <a class="termref">accessibility
After discussing, I think we agreed that "If specified, expose the value of the attribute as the initial value of the `input`. User Agents MUST expose the modified value of the input to the <a class="termref">accessibility tree</a>." belongs in it's own section about all inputs that have attributes (like `value` or `checked`) who's default value is set by the `content attribute`. See the spec: https://html.spec.whatwg.org/multipage/input.html#attr-input-value

This can happen here or in a follow up.

2022-04-27 21:06 UTC, spectranaut commented on index.html
> +                If specified, expose the value of the attribute as the initial value entry of the `input` element.
Can we not say what these mappings are though? Do we know how the accessibility API for the different platforms surface the value of a `input [type="email"]` etc? Like AXValue for Mac?

2022-04-27 21:10 UTC, cookiecrook requested changes

2022-04-27 21:10 UTC, cookiecrook commented on index.html
> +                  <a data-cite="accname-1.2/#dfn-accessible-description">accessible description</a>, or is not mapped (see comments).
Editorial: I think this is phrased ambiguously:

Intention: "either it's:
- mapped (to name or description) or 
- not mapped."

As phrased with the 3-part serial comma: "either it's mapped to:
- name,
- description, or 
- not mapped" (seems like ~"mapped to not mapped")

2022-04-27 21:10 UTC, cookiecrook commented on index.html
> +                  <a data-cite="accname-1.2/#dfn-accessible-description">accessible description</a>, or is not mapped (see comments).
Substantive: I think there are scenarios where implementations may still wish to map it even if it's not used by name or description. Leaving that follow-on mapping optional before the final "is not mapped."

For example, I think after aria-description is mapped, browsers still want to expose the title here as AXHelp in AX API.
```html
<button aria-label="foo" aria-description="bar" title="bop">bif</button>
```

2024-09-19 23:49 UTC, rahimabdi commented
@scottaohara I tried to migrate this one but it is indeed complex; it looks like there are several changes that have already been made in spec (e.g., specifying reset, button for <input> type) so parts of this PR may no longer be needed. The spec formatting has also changed since 2022 so I was unsure if you wanted to keep what we currently have in spec (e.g., input type=reset, type=submit as separate items) vs. this original PR where all of these would be contained in a single table.

If it's OK, I'll leave this one to you to determine what actually needs to be migrated to the mono repo.

2024-11-08 22:51 UTC, scottaohara commented
migrated to https://github.com/w3c/aria/pull/2373.  closing this pr

2024-11-08 22:51 UTC, closed without merging