Addition: inert attribute mappings
w3c/html-aam pull request #410
Opened 2022-05-31 23:23 UTC by scottaohara

closes #399
closes #295

add `inert` attribute and mappings.

wondering if these need to call out that subtree elements should not be focusable re: their mappings, or if the comment here is sufficient?  any other input on additional mappings that may need to be called out here are welcome.

2022-07-08 15:13 UTC, scottaohara commented
Note: I've been drafting updates to the HTML spec for the inert subtree/attribute section.   I will reference that here when the PR is made.

2022-07-08 19:59 UTC, spectranaut requested changes
Couple questions :)

2022-07-08 19:59 UTC, spectranaut commented on index.html
> +                <p>An inert element or the elements of an inert element's subtree cannot receive keyboard focus, nor will they respond to pointer events.</p>
Once you land guidance in the HTML spec, do you need to reiterate this here, rather than just link? Same with your question in the description: `wondering if these need to call out that subtree elements should not be focusable re: their mappings, or if the comment here is sufficient?`

Or does having a focusable subtree element have an effect on the mapping? In which case you should call it out. I think the answer is no, just checking.

2022-07-08 19:59 UTC, spectranaut commented on index.html
> +                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.</p>
What does "escape inertness" mean for html-aam implementations? That the attribute should be ignored? Maybe we should say that?

2022-07-08 20:45 UTC, scottaohara commented on index.html
> +                <p>An inert element or the elements of an inert element's subtree cannot receive keyboard focus, nor will they respond to pointer events.</p>
the guidance to add is mainly author guidance, not implementor.  and the implementor guidance there that i am going to touch on is reflective of the mapping here.

2022-07-08 20:50 UTC, scottaohara commented on index.html
> +                <p>A `dialog` element can escape inertness of its inert ancestor when the `dialog` is modal and rendered in the browser's
```suggestion
                <p>A `dialog` element can escape an inert subtree when the `dialog` is in the modal state, and rendered in the browser's 
```

2022-07-08 20:56 UTC, scottaohara commented on index.html
> +                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.</p>
```suggestion
                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.  A modal dialog, or its <a>flat tree</a> descendants can also become <a>inert</a>.  See <a data-cite="interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a></p>
```

2022-07-08 21:01 UTC, scottaohara commented on index.html
> +                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.</p>
@spectranaut was using language from HTML.  have revised and expanded on that part of the comment, linking back to HTML for more info.

2022-07-08 21:28 UTC, scottaohara commented on index.html
> +                <p>An inert element or the elements of an inert element's subtree cannot receive keyboard focus, nor will they respond to pointer events.</p>
re: my question about focusing.  I personally do not think that needs to be called out here.  it's already mentioned in the HTML spec, so removing the ability for the element/its subtree to be focused in effect removes the mappings related to being focusable.  but if i'm wrong on that, then i'd want to be told what needs to be mentioned here beyond the comment reiterating that the element and/or would-be focusable elements in its subtree cannot receive focus.

2022-07-08 21:28 UTC, scottaohara commented
@spectranaut thank you for the review

2022-07-08 23:16 UTC, spectranaut commented on index.html
> +                <p>An inert element or the elements of an inert element's subtree cannot receive keyboard focus, nor will they respond to pointer events.</p>
Is it odd to add author guidance to the HTML-AAM? I don't remember seeing a lot of author guidance in any of the AAMs, seems like that would mostly belongs in ARIA or HTML? you are the editor, though, so I defer to you :)

2022-07-08 23:25 UTC, spectranaut commented on index.html
> +                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.</p>
I'm afraid I'm still confused, if I had to implement this I wouldn't be positive what to do. "aria-hidden" prunes the subtree, so does this mean we have to go searching through the subtree of all aria-hidden elements for a dialog element with aria-modal="true", and check whether it is in the "top layer"?

Also what are the "flat tree" descendants of something?

2022-07-09 00:13 UTC, scottaohara commented on index.html
> +                <p>An inert element or the elements of an inert element's subtree cannot receive keyboard focus, nor will they respond to pointer events.</p>
by adding author guidance i meant that *that* guidance is going into the HTML spec and even further guidance would go to MDN.  No author guidance would go here.

2022-07-09 00:50 UTC, scottaohara commented on index.html
> +                  <a href="https://fullscreen.spec.whatwg.org/#top-layer">top layer</a>.</p>
those were supposed to be links to their definitions that i hadn't gotten around to getting yet.

but, per your feedback, i've revised/reduced the commentary here again.  This is just for the mapping that needs to occur for the attribute, which is aria-hidden=true.  The rest of the comments are meant to signify expected behaviors.  If more clarity is needed for some of the concepts/terms i was referencing that were defined in other specs, then we should probably make them more clear there, rather than expanding on their meaning in comments here.

thank you for this, this was helpful to keep me from over complicating this.

2022-10-11 12:08 UTC, scottaohara commented
cc @cookiecrook and @jcsteh for feedback and anything else you think needs to be called out in this spec for `inert`?  Please see the companion HTML PR for `inert` that incorporates your feedback into that specification.
https://github.com/whatwg/html/pull/8122

2023-02-18 21:26 UTC, zcorpan commented
Hmm, so `aria-hidden=true` make the whole subtree be hidden, even if a descendant has `aria-hidden=false` (like CSS `display: none`). Maybe we need something in ARIA that is akin to CSS `visibility`, which can be `hidden` on an element and a descendant can still be shown with `visibility: visible`, to property define a mapping for `inert`?

2023-02-18 21:43 UTC, zcorpan commented
Demo of modal dialog inside `<div inert>`:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/11311

In Chrome, Safari, Firefox, the button "show (in inert div)" is not clickable, but the "close" button in the modal dialog is.

2023-02-21 05:15 UTC, JAWS-test commented
> In Chrome, Safari, Firefox, the button "show (in inert div)" is not clickable, but the "close" button in the modal dialog is.

On Windows I get a different result: in Firefox both buttons are clickable and the inert area is fully passed to the Accessbility API

2023-02-21 23:27 UTC, zcorpan commented
Sorry, I meant Firefox Nightly. (`inert` is not yet enabled on release because this spec change is not yet implemented, see https://bugzilla.mozilla.org/show_bug.cgi?id=1767561 )

What I mean to show with the demo is that a modal `dialog` should itself be not-inert, even if it has an ancestor with an `inert` attribute.

2023-02-28 23:07 UTC, cookiecrook commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
How should a `<div role="dialog">` or a `<div role="menu">` achieve the same?

2023-03-01 12:09 UTC, scottaohara commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
possibly by using the popover attribute, though i don't believe that functionality is available right now.  we should open an issue for that separate from this.

2023-03-02 07:09 UTC, cookiecrook commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
As I read it, popover is not intended for modals like <div role="dialog" aria-modal="true">. The Dialog API is the only option for a modal. Regardless, I agree that's addressable as a separate issue.

2023-03-02 07:09 UTC, cookiecrook approved these changes

2023-03-02 12:08 UTC, zcorpan commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
Right, ARIA would need a way of unhiding a child, see https://github.com/w3c/html-aam/pull/410#issuecomment-1435772527

I can file a spec issue.

2023-03-02 12:11 UTC, zcorpan commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
You had filed one already :) https://github.com/w3c/aria/issues/1256

2023-03-03 08:11 UTC, cookiecrook commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
That's specifically for aria-hidden. I don't think aria should be able to un-inert an inert descendant.

2023-03-03 12:02 UTC, zcorpan commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
I'm now confused what you mean with your first message in this thread.

2023-03-03 15:44 UTC, scottaohara commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
dialog is the only element, when shown as a modal, which can escape its parent inert element and become re-exposed in the top layer.

so, per James's question, there is presently no way for someone to invoke an accessible ARIA dialog (modal or otherwise), or a menu if someone wanted to trap focus/screen readers in those elements, if it was contained within an inert container.

though popover is not allowed for HTML modal dialogs, the attribute does send an element to the top layer, so my mention of the attribute is that _it_ could be a way for someone to do something like:

```
<div inert> <!-- attribute added when nested button is activated -->
  <button aria-haspopup=menu ...>
     invokes menu and sets parent to inert
  </button>
  <div role=menu popover ...> 
     <!-- menu items here and even though within an inert container, 
             since its in the top layer now, it COULD now be accessible --> 
   </div>
</div>
```

somewhere in some github thread that i've since lost track of, when implementation of inert was still being discussed, I had mentioned it would be great if `inert=false` would un-inert a child node of an inert parent.  I don't know understand the rational as to why that wasn't entertained further, other than potential implementation complexity.  But back to James's original question, because of that decision there is no way to do what James was asking with HTML now, and `aria-hidden=false` wouldn't/shouldn't be expected to be a way to achieve this, as even if it did re-expose a part of the inert content, by itself it wouldn't undo the browser preventing click/focus to go to the aria-hidden=false content (as applicable if it were to consist of actionable elements)

2023-03-03 16:21 UTC, scottaohara commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
marking this thread as unresolved just to make sure this related discussion about inert/aria-hidden=false isn't missed by those being directed to this issue.

2023-03-03 16:33 UTC, scottaohara commented
@zcorpan per your previous comment
>Edit: or at least a spec hook to do so, which html-aam can use to explain modal dialog in an inert subtree.

with linked example and 
>What I mean to show with the demo is that a modal dialog should itself be not-inert, even if it has an ancestor with an inert attribute.

to my understanding that's already specified in HTML 6.3.1 Modal dialogs and inert subtrees - reference in this PR.  So i don't think we need anything else?

Re: your example contains a button and the dialog in the inert subtree, the dialog is spec'd to escape it. "subject escapes inertness of ancestors" so that's why the button, and its contents are accessible.

followed on by the note
>The [dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) element's [showModal()](https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-showmodal) method causes this mechanism to trigger, by [adding](https://fullscreen.spec.whatwg.org/#top-layer-add) the [dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) element to its [node document](https://dom.spec.whatwg.org/#concept-node-document)'s [top layer](https://fullscreen.spec.whatwg.org/#top-layer).

again, per my response in the comment thread with James, HTML could leverage this to allow popovers to also escape inert, since they too go to the top layer.  But per your example and the button that invokes such elements being within an inert parent - this would likely require the topic of `inert=false` to be re-opened.

Edit: however i also realize i may be reading way too much into the note and what "this mechanism" really means.  but if i'm wrong, maybe that could use some clarification?

2023-03-08 16:24 UTC, zcorpan commented
I think the HTML spec is correct about which nodes are inert and which are not, but this PR mapping the `inert` attribute to `aria-hidden=true` (which makes the element itself and all of its descendants hidden in the a11y tree) doesn't match the HTML spec because it means a descendant modal dialog (which should be uninerted) is still hidden in the a11y tree.

More correct would be to say something like "Nodes that are [inert](https://html.spec.whatwg.org/multipage/interaction.html#inert) are not exposed to an accessibility API. Note: an inert node can have descendants that are not inert (e.g. a modal `dialog` element in HTML). Note: This is similar to `aria-hidden`, except `aria-hidden=true` will unconditionally hide all descendants."

2023-03-08 18:40 UTC, scottaohara commented
@zcorpan re:
>Note: an inert node can have descendants that are not inert (e.g. a modal dialog element in HTML).

will that be true for any other element aside from modal dialogs?  my understanding is that's not true right now, and per my mention of `inert=false` not being entertained, is this actually something that would happen?

Seems the PR could either be updated to specifically mention that if an element (a modal dialog) escapes being inert, then it should no longer be considered aria-hidden=true.  Or, the PR is further adjusted to be more inline with your suggestion that inert doesn't directly map to aria-hidden=true, but it and its subtree behave similarly, but descendants of an inert parent can be marked as not inert - e.g., a modal dialog.

@cookiecrook @aleventhal thoughts on the above?  and specifically, are there any other platform mappings we'd need to note here if the attribute isn't just referring to aria-hidden's mappings in core aam?

2023-03-09 00:22 UTC, cookiecrook commented
I think Simon's normative suggestion and first note are correct:

> Nodes that are [inert](https://html.spec.whatwg.org/multipage/interaction.html#inert) are not exposed to an accessibility API. Note: an inert node can have descendants that are not inert (e.g. a modal dialog element in HTML).

But I would not include the second note:

> ~~Note: This is similar to aria-hidden, except aria-hidden=true will unconditionally hide all descendants.~~

As that may change further with https://github.com/w3c/aria/issues/1256 and the implementations don't currently align on that statement either.

2023-03-09 10:41 UTC, zcorpan commented
@scottaohara it might be true in the future if we introduce other ways to escape inertness.

2023-03-09 12:33 UTC, scottaohara commented
@cookiecrook @zcorpan thank you both.  i'll work on getting this updated.

should we actually update the ARIA spec to mention inert in https://www.w3.org/TR/wai-aria-1.2/#tree_exclusion

that seems it might be a good place for a longer explanation of how to handle inert / potential children which are no longer inert, which could then be linked to from html aam / other aams which might need it.

2023-03-22 12:31 UTC, scottaohara commented on index.html
> +                  Nodes that are inert are not exposed to an accessibility API.
```suggestion
                  Nodes that are <a data-cite="html/interaction.html#inert">inert</a> are not exposed to an accessibility API.
```

2023-03-22 14:37 UTC, zcorpan approved these changes

2023-03-22 22:05 UTC, cookiecrook approved these changes

2023-03-28 17:05 UTC, merged

2023-03-29 00:24 UTC, alice commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
> it would be great if `inert=false` would un-inert a child node of an inert parent

Coming in very late, and obviously this has no bearing on the outcome of this PR, but I talked a bit about the rationale here: https://www.igalia.com/chats/alice-and-rob (you can search for "one way" in the transcript rather than listen to the whole rambling conversation).

2023-03-29 10:50 UTC, scottaohara commented on index.html
> +                  See also <a data-cite="html/interaction.html#modal-dialogs-and-inert-subtrees">Modal dialogs and inert subtrees</a>.
@alice thank you for the link and background!