Addition: clarify when to expose a required element as invalid
w3c/html-aam pull request #429
Opened 2022-07-13 17:21 UTC by scottaohara

Not the happiest with my initial wording here, but figure maybe others can review and help provide some better text.

The intent here is to tell browsers to NOT expose a required field as invalid until after a user has interacted with it in some way (blur and left empty or entered an invalid value, or attempted to submit a form of required elements without filling them in).

Closes #394

related to https://github.com/w3c/aria/issues/1488

and Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1318969#c17

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/pull/429.html" title="Last updated on Oct 3, 2023, 2:06 PM UTC (29f7805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/429/6bf7d41...29f7805.html" title="Last updated on Oct 3, 2023, 2:06 PM UTC (29f7805)">Diff</a>

2022-07-17 05:04 UTC, JAWS-test commented
I think it's very good because it would finally solve this old problem. I only wonder if it is technically possible, because the HTML specification specifies something else and in my opinion the HTML specification and this specification would contradict each other.

2022-12-13 16:19 UTC, scottaohara commented
Update:

Chromium browsers have implemented this change and now the invalid state is not announced until a user has entered an invalid value to a field.

Safari on macOS also does not announce the invalid state with an untouched field.  Safari _doesn't_ announce a field as invalid when it has an incorrect entry - there is a browser form message that appears that indicates the incorrect entry, but the field itself does not expose an aria-invalid=true.  

Firefox announces an untouched required field as invalid.

2023-02-28 23:29 UTC, cookiecrook requested changes

2023-02-28 23:29 UTC, cookiecrook commented on index.html
> +                  (<a class="core-mapping" href="#ariaInvalidFalse">`aria-invalid="false"`</a>).
I find the and/or prioritization of the long sentence difficult to parse. How about adding 1), 2), like below, or break into an AND list where the LIs can encapsulate the ORs.

```suggestion
                  If an element is <a data-cite="html/input.html#concept-input-required">required</a>, user agents MUST NOT expose the 
                  element with an intitial invalid state (<a class="core-mapping" href="#ariaInvalidTrue">`aria-invalid="true"`</a>). 
                  The user agent SHOULD expose the invalid state only after <strong>1)</strong> a user has purposefully interacted with a required element, or attempted to submit a form and <strong>2)</strong> the element, or elements, do not meet
                  <a data-cite="html/form-control-infrastructure.html#constraint-validation">constraint validation</a>. Until then, user agents MUST expose the elements as
                  (<a class="core-mapping" href="#ariaInvalidFalse">`aria-invalid="false"`</a>).
```

2023-03-08 21:28 UTC, scottaohara commented
thanks @cookiecrook.  i pulled in your suggestion and also broke the paragraph into two parts.

2023-03-08 21:32 UTC, scottaohara commented
<s>this pr should pull in the work steve started in #395</s>

edit: no, that should be its own PR still.

2023-03-22 22:03 UTC, cookiecrook approved these changes

2023-10-03 14:06 UTC, scottaohara commented on index.html
> +          <li>03-Oct-2023: Clarify when to expose required field as invalid. See <a href="https://github.com/w3c/html-aam/pull/429">GitHub PR 429<a/>.</li>
```suggestion
          <li>03-Oct-2023: Clarify when to expose required field as invalid. See <a href="https://github.com/w3c/html-aam/pull/429">GitHub PR 429</a>.</li>
```

2023-10-03 14:10 UTC, scottaohara commented
per the approving review and the fact the chrome bug has been marked as fixed, i'm merging this PR.

2023-10-03 14:11 UTC, merged