accessible description computation revision
w3c/html-aam pull request #433
Opened 2022-08-29 16:25 UTC by scottaohara

This PR removes the various individual element accessible description computations and instead combines them into a single stepped computation listing, as apart from `summary`, `table` and `input type=button|reset|submit`, they were all the same.

The revised accDescription still calls out these special cases (so nothing in the computation has changed here).  We should probably discuss these again in the future.

This PR also includes `aria-description` as being part of the first step in the accDescription computation (similar to how aria-label/aria-labelledby are mentioned as the first step in the element naming computations).  AccName defines the priority of these two attributes in the accDesc computation.

This PR is related to https://github.com/w3c/accname/pull/69

2022-08-29 16:31 UTC, scottaohara commented on index.html
> +          If the element has an <a data-cite="wai-aria-1.2/#aria-describedby">`aria-describedby`</a> or <a data-cite="wai-aria-1.2/#aria-description">`aria-description`</a> attribute the <a data-cite
aria-description is not in ARIA 1.2 - so this needs to change to https://w3c.github.io/aria/#aria-description

2022-08-29 16:32 UTC, scottaohara commented on index.html
> +          If the element has an <a data-cite="wai-aria-1.2/#aria-describedby">`aria-describedby`</a> or <a data-cite="wai-aria-1.2/#aria-description">`aria-description`</a> attribute the <a data-cite
though, it seems that HTML AAM should probably just always link to the latest drafts of docs, rather than different versions of the specs

2022-09-01 17:53 UTC, MelSumner requested changes
This PR certainly simplifies things and makes it a lot clearer. 

I think you made a valid point with

> it seems that HTML AAM should probably just always link to the latest drafts of docs, rather than different versions of the specs

Should the links be updated before approve/merge?

2022-09-27 18:53 UTC, spectranaut requested changes
what do you think of these changes @scottaohara? when I first read you suggested change is stuck me as not as clear as the original table in the corrosponding accname pr.

2022-09-27 18:53 UTC, spectranaut commented on index.html
> +            <li>If a `table` element, has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> that is a `caption` element and it was not used as the <a data-cite="accname-1.2/#dfn-a
```suggestion
            <li>
              If the element is a `table` element:
              <ol>
                <li>If the `table` element has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> that is a `caption` element, then use the subtree of the first `caption` if the `caption` was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
              </ol>
            <li>
```

2022-09-27 18:53 UTC, spectranaut commented on index.html
> +            <li>If a `summary` element, use the element's subtree if it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
```suggestion
            <li>
              If the element is a `details` element:
              <ol>
                <li>Use the element's `summary` child if the `summary` was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
              </ol>
            </li>
```

2022-09-27 18:53 UTC, spectranaut commented on index.html
> +            <li>If an `input` element whose type attribute is the `button`, `submit` or `reset` state has a `value` attribute and it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name
```suggestion
           <li>
             If the element is an `input` element whose type attribute is the `button`, `submit` or `reset`:
             <ol>
               <li>Use the contents of the html `value` attribute if the `value` attribute was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
             </ol>
           </li>
```

2022-09-27 20:39 UTC, spectranaut commented on index.html
> +          If the element has an <a data-cite="wai-aria-1.2/#aria-describedby">`aria-describedby`</a> or <a data-cite="wai-aria-1.2/#aria-description">`aria-description`</a> attribute the <a data-cite
I feel like this makes me feel like all of our specs should be evergreen? If you link from ARIA 1.3 to core-aam and then core-aam links back to the working draft? Seems odd to come back to a draft you didn't didn't start out in?

Anyway, for this, though, I agree.

2022-09-27 21:45 UTC, stevefaulkner approved these changes

2022-09-28 18:45 UTC, scottaohara commented
@spectranaut appreciate the suggestions.  i'm going to adjust just a couple of things, but yeh, that helps call out the element and its special condition better than as one lumpy sentence.

2022-09-28 19:11 UTC, scottaohara commented on index.html
> +            <li>If a `summary` element, use the element's subtree if it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
FYI, the details element does not get a name from the summary element. This was wrong in the core aam PR and why i changed it here.

2022-09-28 19:48 UTC, spectranaut commented on index.html
> +            <li>If a `summary` element, use the element's subtree if it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.</li>
ohhh I see thxx

2022-09-28 19:54 UTC, spectranaut commented on index.html
> +                <li>has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> `caption` element, use the subtree of the first `caption` element if it was not used as the <a data-cite=
@scottaohara I think each bullet should be a full sentence thus the verbosity of my suggestions -- "If a table element" is not a full sentence and neither is "has a caption element, us the subtree of the first...."

but you are the editor so ultimately up to you :)

2022-09-29 17:51 UTC, scottaohara commented on index.html
> +                <li>has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> `caption` element, use the subtree of the first `caption` element if it was not used as the <a data-cite=
hmm... understand your comment. just seems that if more verbosity is needed to introduce each single item sub-list, then maybe they should just stay sentences instead of breaking them apart, so as not having to say "if the element is a table element" and then start the new sentence with "if the table element..." again.

2022-09-29 18:32 UTC, spectranaut commented on index.html
> +                <li>has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> `caption` element, use the subtree of the first `caption` element if it was not used as the <a data-cite=
I see -- I now that I'm looking I realize I don't even suggest full sentences, so maybe that isn't what I'm after. I think this comes down to a preference.

Personally, if I'm reading the spec, I'd want to read "If the element is a table element" rather than "if a table element". If I was reading this step, I'd panic a little at this line. My internal dialog: "If a table element.... if a table element... if WHAT a table element??????"  I want the spec to tell me WHAT specifically I'm checking to be a table element. Even if it is obvious from context clues.

For example in this change I suggested: https://github.com/w3c/html-aam/pull/433#discussion_r981593862

I want each bullet to be an actionable step with all the objects/parts of that step included in the language of the step. I'd prefer there to be repetition rather than anything left out.
- action: check if the element is a table element -> spec: "if the element is a `table` element"
- action: check if the table element has a caption and the caption has not been already used, use the subtree -> spec: "If the `table` element has a child that is a `caption` element, then use the subtree of the first `caption` if the `caption` was not used as the accessible name"

2022-09-29 22:54 UTC, scottaohara commented on index.html
> +                <li>has a <a href="https://dom.spec.whatwg.org/#concept-tree-child">child</a> `caption` element, use the subtree of the first `caption` element if it was not used as the <a data-cite=
@spectranaut thanks again, and yeh, definitely seems a preference thing, so i'm trying to adjust a bit more to try and meet in the middle.

i've reverted back to sentences and instead adjusted the intro sentence to the sub-lists to try to make it more clear without adding in redundancies.

2022-09-29 23:00 UTC, spectranaut approved these changes
looks good to me now :)

2022-09-29 23:00 UTC, spectranaut commented on index.html
> +              `summary` element, use the element's subtree if it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.
```suggestion
              a `summary` element, use the element's subtree if it was not used as the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.
```

Add an "a"

2022-10-26 13:19 UTC, scottaohara commented
merging this.  This issue https://github.com/w3c/html-aam/issues/437 will be where the spec is updated to link to the latest editors' draft of the ARIA specs

2022-10-26 13:19 UTC, merged