Clarification: label element and for attribute
w3c/html-aam pull request #448
Opened 2022-12-08 15:08 UTC by scottaohara

This PR clarifies some of the wording in the `label` element mappings where, for instance, UIA was written in a way that was specifically calling out labelling the `input` element - but there are a number of labelable elements that are not `input`.  Rather than say all of them or even say 'form controls' which is also not necessarily accurate, instead mention and link to the HTML spec's definition and listing of labelable elements.

The `label[for]` attribute was updated to consistently indicate that it's used for accname by all the platforms.  UIA's 'not mapped' text was replaced with a version of the text that existed in the `label` element's UIA mapping.  MSAA/IA2 mappings were updated to reference the labelable element section from HTML.

note: this work was done as I noticed these things needed clarifying while making other additions to #402 today.

2022-12-08 22:19 UTC, spectranaut requested changes
You know I think its a bit weird that for the label element description,  UIA + IA2 have the same "logic" but its worded differently, if that makes sense. And if my comment is correct on ATK, include that as well.

Like you could just choose one or two and swap out "property" or "relation" with "relation" or "property" and the name of the relation or property, etc. Otherwise it's kind of weird because if you are referring to this spec you might thing the differences are more complicated when they really are the same concepts!

For example:
* `LabeledBy` attribute points to a with a `labelable element` that is a child to the `label` or referred to by the `label` elements `for` attribute

2022-12-08 22:19 UTC, spectranaut commented on index.html
> +                  `IA2_RELATION_LABEL_FOR` with a <a href="#el-label">`label`</a> and referred <a data-cite="html/forms.html#category-label">labelable element</a>
I think I like the originally wording a little better!

you wrote:
* `IA2_RELATION_LABEL_FOR` with a `label` and referred `labelable element` that is a child to the `label` or referred to by the `label` elements `for` attribute

I think maybe you just want:
* `IA2_RELATION_LABEL_FOR` with a `labelable element` that is a child to the `label` or referred to by the `label` elements `for` attribute

2022-12-08 22:19 UTC, spectranaut commented on index.html
> +                  `ATK_RELATION_LABEL_FOR` for a child form element or form element referred by <a href="#att-for-label">`for`</a> attribute.
did you miss this one -- should this also be `labelable elements` not form element? And shouldn't we care when there is a `labelable element` contains in the `label` element here, as well?

2022-12-08 22:19 UTC, spectranaut commented on index.html
> +                  the element points to the UIA element for the `label` element.
nit: it's weird looking that this is also not in a `<p>`, maybe it should be?

2022-12-08 22:32 UTC, scottaohara commented on index.html
> +                  `IA2_RELATION_LABEL_FOR` with a <a href="#el-label">`label`</a> and referred <a data-cite="html/forms.html#category-label">labelable element</a>
yes i think i messed this one up.  thank you!

2022-12-12 17:31 UTC, scottaohara commented on index.html
> +                  the element points to the UIA element for the `label` element.
there are a bunch of markup bits that need to be fixed in this spec.  The use of `<p>` here would introduce some extra spacing that other cells don't have.  Rather, I'll wrap these each in divs so they're consistent and not introduce variants in the styles.

2023-03-08 20:20 UTC, scottaohara commented
re-requesting review @spectranaut @jnurthen @adampage

2023-03-09 00:11 UTC, adampage approved these changes
This is a helpful clarification. 🚀

2023-03-22 12:36 UTC, scottaohara commented on index.html
>                    <span class="type">Other properties:</span>
```suggestion
                  <span class="type">Relations:</span> 
```

2023-03-22 12:36 UTC, scottaohara commented on index.html
>                  <div class="properties">
```suggestion
                <div>
```

2023-03-22 12:38 UTC, merged