contextual role concept proposal
w3c/html-aam pull request #484
Opened 2023-05-11 16:39 UTC by scottaohara

closes #375

The purpose of this proposal is both to resolve the issue that "scoped" was an undefined term that was used to indicate when certain elements would expose particular ARIA roles or not.  However, in the year of noodling on this, other activities to revise what "owned" means in ARIA, the idea of a minimum role, as well as the fact there were other elements in HTML that have "scoped" or "contextual roles" that are based on heuristics, rather than defined standards, became relevant.

A change to hopefully help simplify the implementations of contextual roles is that this proposal is aiming to tie the role of an element based on its a11y tree ancestry, rather than based on specific HTML elements in the DOM.

This PR represents the initial draft of the proposal.  Other work to explicitly call out the elements that have contextual roles, what roles they need to adjust to, and other wording revisions to replace "scoped" with the new term would still need to be made.

## Implementation

* WPT tests: [LINK]()
* Implementations (link to issue or when done, link to commit):
   * WebKit: [ISSUE]()
   * Gecko: [ISSUE]()
   * Blink: [ISSUE]()

2023-05-11 16:56 UTC, scottaohara reviewed
more instances of converting undefined terms to temporary STRONG elements.  fix of a typo

2023-05-11 16:56 UTC, scottaohara commented on index.html
> +        An element with a <dfn>contextual role</dfn> is one whose implicit WAI-ARIA role semantics are based on its anestral <a>accessibility tree</a> relationship to
```suggestion
        An element with a <STRONG>contextual role</STRONG> is one whose implicit WAI-ARIA role semantics are based on its ancestral <a>accessibility tree</a> relationship to 
```

2023-05-11 16:56 UTC, scottaohara commented on index.html
> +        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <a>minimum role</a>, if applicable.
```suggestion
        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <STRONG>minimum role</STRONG>, if applicable. 
```

2023-05-11 16:56 UTC, scottaohara commented on index.html
> +          An <code>aside</code> element has an implicit WAI-ARIA role mapping of <code>complementary</code> only when the element is an <a>accessibility child</a> of
```suggestion
          An <code>aside</code> element has an implicit WAI-ARIA role mapping of <code>complementary</code> only when the element is an <STRONG>accessibility child</STRONG> of 
```

2023-05-11 16:56 UTC, scottaohara commented on index.html
> +        <p>A <code>section</code> element has an implicit WAI-ARIA role mapping of <code>region</code> only when the element is provided an <a>accessible name</a>.</p>
```suggestion
        <p>A <code>section</code> element has an implicit WAI-ARIA role mapping of <code>region</code> only when the element is provided an <STRONG>accessible name</STRONG>.</p>
```

2023-05-11 20:12 UTC, spectranaut requested changes
I think it would be nice to see at lease one example of "contextual role" being used in the mapping tables.

I really think this is the right direction!! I can help nit pick the specific wording ad infinitum though.

2023-05-11 20:12 UTC, spectranaut commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
Do we want to start off with something even vaguer and more all encompassing, for example:

> An element with a contextual role is one whose implicit WAI-ARIA role semantics are dependent on the existence of other elements in the accessibility tree or the existence of certain attributes. 

Maybe that is too vague? Maybe is an "accessible name" an "attribute"? Can we imagine other attributes might effect a role? Like `tabindex`?

Regardless I do object to a sentence starting with `Or, `. Here is another try, just to try things out:

> An element with a contextual role is one whose implicit WAI-ARIA role semantics are effected by one or more of the following constraints:
> - A required ancestral relationship with other elements in the accessibility tree.
> - The existence of an accessible name.

2023-05-11 20:15 UTC, spectranaut commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
oh wow when I mentioned tabindex, I just remembered this had an effect on the "minimum role" concept. Honestly, it seems, minimum role is actually a "contextual role", and maybe... we don't need these things to be separately defined?

2023-05-11 21:13 UTC, scottaohara commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
i did have that thought as well... but the rational i kept coming back to as to why they should be separate is that contextual roles are elements that have defined roles, but do to both valid and invalid use, their role may need to adjust.  These behaviors largely exist now as either defined for specific elements, or are undefined behaviors that presently occur.

where as minimum roles are really only for elements that aren't meant to be anything more than generic or not exposed to the a11y api, but due to valid use of HTML, they need to have a minimum role based on the attribute that was used on the element.  minimum roles are not presently implemented, unlike most if not all of the contextual roles.

the distinctions could be clearer with further edits... but i do completely agree that the concepts are related and could be merged into a single section.  Just two different tracks, where i really don't want one concept to be held up by the other (minimum role being more important imo)

2023-05-15 17:17 UTC, spectranaut commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
ok I can easily see them as both separate or under the same umbrella, and I see your point about not holding things up.

2023-05-17 23:33 UTC, cookiecrook requested changes

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
I like the first sentence phrasing of "ancestral" context, but I have a suggestion for the second to broaden it, but keep the name/label as an concise, understandable example.

```suggestion
        another element or elements. Or, an element whose computed role is dependent upon whether it has other associated accessibility information, such as an author-provided accessible label. 
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        and would therefore expose a computed role appropriate for that context.
Word-smithing plus examples.

```suggestion
        For instance, an element that is an <strong>accessibility child</strong> of its required <strong>accessibility parent</strong> would expose a computed role for its given context, such as a list item (<code>li</code>) within an unordered list (<code>ul</code>). However, the same element might be used within a different markup pattern and could therefore expose different contextually-dependent computed roles, such as a labeled <code>section</code> element (role <code>region</code>) versus an unlabeled <code>section</code> element (role <code>generic</code>).
```

Can we think of a specific example that works for both? If so that'd be better than the sectioning content examples, which are less easy to understand and care about than a simple list.

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <STRONG>minimum role</STRONG>, if applicable.
consistency nit
```suggestion
        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <strong>minimum role</strong>, if applicable. 
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +          A <code>li</code> element has an implicit WAI-ARIA role mapping of <code>listitem</code> only when the element is an <STRONG>accessibility child</STRONG> of a
```suggestion
          A <code>li</code> element has an implicit WAI-ARIA role mapping of <code>listitem</code> only when the element is an <strong>accessibility child</strong> of a 
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        &lt;li>...&lt;/li> &lt;!-- role=listitem -->
```suggestion
        &lt;li>...&lt;/li> &lt;!-- computed role `listitem` -->
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        &lt;li>...&lt;/li> &lt;!-- not role=listitem -->
```suggestion
        &lt;li>...&lt;/li> &lt;!-- computed role `generic`, not `listitem` -->
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +          An <code>aside</code> element has an implicit WAI-ARIA role mapping of <code>complementary</code> only when the element is an <STRONG>accessibility child</STRONG> of
```suggestion
          An <code>aside</code> element has an implicit WAI-ARIA role mapping of <code>complementary</code> only when the element is an <strong>accessibility child</strong> of 
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +          &lt;aside>...&lt;/aside> &lt;!-- not role=complementary -->
```suggestion
            &lt;aside>...&lt;/aside> &lt;!-- computed role `generic`, not `complementary` -->
            ...
            &lt;aside aria-label=named>...&lt;/aside> &lt;!-- computed role `complementary` -->
          &lt;/article>
          ...
          &lt;aside>...&lt;/aside> &lt;!-- computed role `complementary` -->
        &lt;/main>
        &lt;aside>...&lt;/aside> &lt;!-- computed role `complementary` -->
        ...
        &lt;footer>
          ...
          &lt;aside>...&lt;/aside> &lt;!-- computed role `generic`, not `complementary` -->
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +        <p>A <code>section</code> element has an implicit WAI-ARIA role mapping of <code>region</code> only when the element is provided an <STRONG>accessible name</STRONG>.</p>
```suggestion
        <p>A <code>section</code> element has an implicit WAI-ARIA role mapping of <code>region</code> only when the element is provided an <strong>accessible name</strong>.</p>
```

2023-05-17 23:33 UTC, cookiecrook commented on index.html
> +      &lt;section>...&lt;/section> &lt;!-- not role=region --></code></pre>
```suggestion
      <pre><code>&lt;section title="accessible name">...&lt;/section> &lt;!-- computed role `region` -->
      ...
      &lt;section aria-label="accessible name">...&lt;/section> &lt;!-- computed role `region` -->
      ...
      &lt;section>...&lt;/section> &lt;!-- computed role `generic`, not `region` --></code></pre>
```

2023-05-18 00:29 UTC, scottaohara commented on index.html
> +        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <STRONG>minimum role</STRONG>, if applicable.
the STRONGs are only in there as placeholders, since I would need to remove these to reference the terms which haven't been published yet, so were breaking the HTML AAM build

2023-05-18 05:39 UTC, cookiecrook commented on index.html
> +        When the conditions for an element's contextual role are not met, it will commonly expose a computed role of `generic` or with a <STRONG>minimum role</STRONG>, if applicable.
okay. I'll mark as resolved/ignored and adjust any more edits

2023-05-18 16:52 UTC, spectranaut commented on index.html
> +        another element or elements. Or, an element whose computed role is reliant on whether the element has been provided an accessible name.
nice I like this suggestion, @cookiecrook

2023-05-19 13:54 UTC, scottaohara commented on index.html
> +        and would therefore expose a computed role appropriate for that context.
@cookiecrook I like these suggestions so i'm going to largely pull them in - but I'm going to be changing the use of "accessible label" back to "name".

2023-05-19 14:28 UTC, scottaohara commented on index.html
> +        and would therefore expose a computed role appropriate for that context.
@cookiecrook re: other examples.

What do you think about mentioning tbody here, per the whole rowgroup conversation?  That'd be an example of a contextual role where it can be ignored until it is given a name or focusable.

Another example we could use in lieu of / in combination with the list item example is the summary of a details, where only under specific conditions is the summary an `html-summary`, and otherwise it would need to be a `role=generic`

2023-10-16 00:48 UTC, cookiecrook commented on index.html
> +        and would therefore expose a computed role appropriate for that context.
🤷 I could go either way. I don't think most authors give much thought to `<tbody>` etc, so I'm not sure it'd be super helpful as an example, but I also don't think it'd be harmful.

2023-11-15 00:47 UTC, rahimabdi commented on index.html
> +      <h3>Exposing HTML Features With Contextual Roles</h3>
This heading may not accurately capture the intent of the section; particularly, the words "HTML Features" used to describe contextual roles and how they're treated. I don't know the best way to describe the new section but if you agree, some alternatives for your consideration: Contextual Roles, Treatment of Contextual Roles, Understanding Contextual Roles, Understanding Contextual Roles and Accessibility Ancestry

2024-08-11 23:01 UTC, rahimabdi commented
Closing, this PR has been migrated to the ARIA monorepo:
- https://github.com/w3c/aria/pull/2218

2024-08-11 23:01 UTC, closed without merging