add mention of image role
w3c/html-aam pull request #498
Opened 2023-08-16 14:54 UTC by scottaohara

Firefox and Safari have implemented/released the update to make image a synonym role for img.  Chromium will be releasing this update soon.

this PR references the image element as mapping to img/image, and adds a comment to reference the synonym addition in ARIA 1.3

2023-08-17 17:21 UTC, cookiecrook commented
Also note that @spectranaut added this to the computed role column, so it's in the spec already. Fine to add another note though.

2023-08-17 17:23 UTC, cookiecrook commented
> Firefox and Safari have implemented/released the update to make image a synonym role for img. Chromium will be releasing this update soon.

And to clarify, this means `img` is a synonym of the now primary role `image` role. Likewise `presentation` is a synonym of the preferred/primary role name, `none`…

2023-08-17 17:35 UTC, scottaohara commented on index.html
> +                <!-- todo: update role map link if/when core aam adds in a specific image role mapping table -->
i question the value in having separate tables in core aam for presentation|none and potentially now img|image

could these not just be one table?

2023-08-17 17:36 UTC, scottaohara commented on index.html
> +                  ARIA 1.3 adds the `image` role as a synonym of the ARIA 1.0 `img` role.
note i know that image is the primary role - but this is using text directly from a note in the ARIA spec.  if we want to change this wording, then we should change the ARIA spec wording too

2023-08-17 20:59 UTC, spectranaut commented on index.html
> +                <!-- todo: update role map link if/when core aam adds in a specific image role mapping table -->
Hmm I see your point, but I don't think its necessary. I think it's ok to be verbose and repeat here, these specs are edited rarely, and I think it makes sense to have an entry for every role. Then we will have a unique link to every role (#role-map-img and #role-map-image). To combine them would introduce a different kind of complexity.

2023-08-17 20:59 UTC, spectranaut commented on index.html
> +                  ARIA 1.3 adds the `image` role as a synonym of the ARIA 1.0 `img` role.
I think this wording is fine.

2023-08-17 21:02 UTC, spectranaut requested changes

2023-08-17 21:02 UTC, spectranaut commented on index.html
> +                <a class="core-mapping" href="#role-map-img">`image`</a>
```suggestion
                <a class="core-mapping" href="#role-map-image">`image`</a>
```

As I said before, I do think there should be (as there is now) an entry for every role in CORE-AAM. And this link should go to "image" role as it suggests.

2023-08-17 21:37 UTC, scottaohara commented on index.html
> +                <a class="core-mapping" href="#role-map-img">`image`</a>
then this PR is blocked on core aam not having an image role entry

2023-08-17 21:41 UTC, scottaohara commented on index.html
> +                <a class="core-mapping" href="#role-map-img">`image`</a>
or we can merge as is, and then update the link once the image role is added to core aam.

i prefer doing that for something so minor, like this.  but will wait if others disagree

2023-08-17 22:55 UTC, spectranaut commented on index.html
> +                <a class="core-mapping" href="#role-map-img">`image`</a>
omg! I was confused by your comment because I was so convinced there was an entry for "image". Tomorrow I'm going to merge the changes related to removing the tables/disclosure, I'll also open a PR adding image, and then you can merge this, how about that?

2023-08-18 21:15 UTC, spectranaut approved these changes

2023-09-25 20:52 UTC, cookiecrook requested changes

2023-09-25 20:52 UTC, cookiecrook commented on index.html
> +                <a class="core-mapping" href="#role-map-img">`img`</a> role
Since `image` is the primary, shouldn't this just be "`image`", not "`img` **_or_** `image`"

2023-09-25 20:52 UTC, cookiecrook commented on index.html
> +                  <a class="core-mapping" href="#role-map-none">`none`</a>
Same issue here... IMO. should be "`none`", not "`presentation` or `none`"

2023-10-03 15:27 UTC, scottaohara commented
have fixed the merge conflicts, and have addressed @cookiecrook's comments.  I"m going to merge this PR and can fast follow with any additional changes / create new issues/prs as necessary

2023-10-03 15:27 UTC, merged