Specify AXAPI behaviour for `low`, `high`, and `optimum` meter attributes.
w3c/html-aam pull request #538
Opened 2024-03-19 21:25 UTC by MReschenberg

Closes #536

Specification based on Safari behaviour/attributes exposed.

2024-03-19 23:31 UTC, jnurthen requested changes
I don't think it is as simple as this. As I understand it `<meter>` can have 3 segments, 
* (1) below `low`, 
* (2) between `low` and `high` 
* (3) above `high`. 
If the `optimum` value fits into (1) then all values within this segment are optimal, values in (2) are suboptimal and values in (3) are critical 
If the optimal value is in (2) then values in (1) and (3) are both suboptimal
If it is (3) then values in (1) are critical, (2) suboptimal and (3) optimal.

These correspond to the visual coloring of green (optimal), orange (suboptimal) and red (critical). 

If no `optimum` value is specified then the optimal segment is segment (2)

Here is the webkit logic https://github.com/WebKit/WebKit/blob/c330ea99229f6bb478dde74497ee652e44a3d7d5/Source/WebCore/html/HTMLMeterElement.cpp#L156

2024-03-19 23:31 UTC, jnurthen commented on index.html
> +        <div class="general">Expose "optimal value" via `AXValueDescription` if &lt;value&gt; is greater than or equal to &lt;high&gt;. Expose "suboptial value" if &lt;value&gt; is less than &lt;high
```suggestion
        <div class="general">Expose "optimal value" via `AXValueDescription` if &lt;value&gt; is greater than or equal to &lt;high&gt;. Expose "suboptimal value" if &lt;value&gt; is less than &lt;high&gt; and greater than or equal to &lt;low&gt;.</div>
```

2024-05-01 01:56 UTC, rahimabdi reviewed
Hi @MReschenberg, I've added comments and recommendations that largely align with @jnurthen's assessment of `optimum` treatment.

2024-05-01 01:56 UTC, rahimabdi commented on index.html
> +        <div class="general">Expose "optimal value" via `AXValueDescription` if &lt;value&gt; is greater than or equal to &lt;high&gt;. Expose "suboptimal value" if &lt;value&gt; is less than &lt;hig
Relevant WebKit code: https://github.com/WebKit/WebKit/blob/c330ea99229f6bb478dde74497ee652e44a3d7d5/Source/WebCore/html/HTMLMeterElement.cpp#L172

This looks correct. We'll also need to add the case for when the `value` is less than "low" (for which this is exposed as "critical value").

2024-05-01 01:56 UTC, rahimabdi commented on index.html
> +        <div class="general">Expose "suboptial value" via `AXValueDescription` if &lt;value&gt; is greater than or equal to &lt;low&gt; and less than &lt;high&gt;. If &lt;value&gt; is less than &lt;l
Relevant WebKit code: https://github.com/WebKit/WebKit/blob/c330ea99229f6bb478dde74497ee652e44a3d7d5/Source/WebCore/html/HTMLMeterElement.cpp#L163

For `low`:

- If `value` is less than or equal to `low`, then `value` = "optimal value"
- if `value` is less than or equal to `high` (but greater than `low`), then `value` is "suboptimal value"
- else, `value` is "critical value"

Also, looks like there is a typo for the word "suboptimal" here.

2024-05-01 01:56 UTC, rahimabdi commented on index.html
> +        <div class="general">Expose "optimal value" via `AXValueDescription` if &lt;value&gt; is greater than or equal to &lt;optimum&gt;.</div>
Relevant WebKit code: https://github.com/WebKit/WebKit/blob/c330ea99229f6bb478dde74497ee652e44a3d7d5/Source/WebCore/html/HTMLMeterElement.cpp#L184

For `optimum`:

- If `value` is greater than or equal to `low` AND `value` is less than or equal to `high` then `value` =  "optimal value"
- Else, `value` = "suboptimal value"

Note that in this case, there is no "critical value".

2024-05-01 02:43 UTC, cookiecrook requested changes
This issue should have an active test case showing this in a more common use case, like an audio meter bouncing quickly and showing critical peak line clipping. 

I’m not sure if this will need new API, or if there is existing API, but I’m reasonably sure `AXValueDescription` is not the ideal way to vend this to AT like VO.

2024-05-02 18:52 UTC, MReschenberg commented
> I’m not sure if this will need new API, or if there is existing API, but I’m reasonably sure `AXValueDescription` is not the ideal way to vend this to AT like VO.

Do you have an alternative attribute in mind? 
It sounds like there's not enough info at this point to make this spec decision, so I'm leaning towards updating firefox's VO implementation to match safari temporarily and leaving this open for discussion.

2024-05-02 22:08 UTC, cookiecrook commented
Likely to be the existing `AXLevelIndicator` but TBD based on the outcome of the linked issue.

2024-09-19 20:24 UTC, rahimabdi commented
Closing, this PR has been migrated to the ARIA monorepo:

- https://github.com/w3c/aria/pull/2339

2024-09-19 20:24 UTC, closed without merging